config/routes.rb
Rails.application.routes.draw do

  root  'users#home'
  get    '/signup',  to: 'users#new'
  resources :users do
    resources :profiles
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :events do
    resources :comments, only: [:create, :destroy, :show] do
      post 'reply', to: 'comments#reply'
    end
    resources :jevents, only: [:create, :destroy]
  end
  resources :circles do 
    resources :jcircles, only: [:create, :destroy]
    
  end
   get 'genre', to: 'events#genre'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :jevents, dependent: :destroy
  has_many :circles, dependent: :destroy
  has_many :jcircles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :profiles, dependent: :destroy
  has_many :jcircle_circles, through: :jcircles, source: :circle
  has_many :jevent_events, through: :jevents, source: :event
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    if logged_in?
      @user = User.find(session[:user_id])
    end
  end
  def show
    puts "======"
    puts params[:id]
    puts "======"
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: params[:id])
    puts "======"
    puts @profile
    puts "======"
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)# 実装は終わっていないことに注意!
    if @user.save
      @user.profiles.create(content: 'よろしくお願いします')
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
   @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        flash[:success] = "更新しました!"
        redirect_to user_path(@user)
    else
         
        render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<% if logged_in? %>
<div class="container">
    <div class="text-center h1 mt-70px">ようこそ！　<%= @user.name%></div>
    <div class="row w-800px mt-100px">
        <div class="card mt-2 mr-2 col-sm " style="height:10rem;">
            <div class="h4 mx-auto mt-3">イベントに参加</div>
            <p class="card-text mx-auto">自分の興味あるイベントを探してみよう</p>
            <div class="btn btn-primary mx-auto" style="width: 15rem;"><%=link_to "探そう", events_path, class:"text-white"%></div>
        </div>
        <div class="card mt-2 col-sm" style="height:10rem;">
            <div class="h4 mx-auto mt-3">サークルに参加</div>
            <p class="card-text mx-auto">気になるサークルに参加しよう</p>
            <div class="btn btn-primary mx-auto" style="width: 15rem;"><%=link_to "探そう", circles_path, class:"text-white" %></div>
        </div>
    </div>
    <div class="row w-800px ">
        <div class="card mt-2 mr-2 col-sm" style="height:10rem;">
            <div class="h4 mx-auto mt-3">イベントを企画</div>
            <p class="card-text mx-auto">自分の興味あるイベントを探してみよう</p>
            <div class="btn btn-primary mx-auto" style="width: 15rem;"><%=link_to "企画してみよう", new_event_path, class:"text-white" %></div>
        </div>
        <div class="card mt-2 col-sm" style="height:10rem;">
            <div class="h4 mx-auto mt-3">サークル作り</div>
            <p class="card-text mx-auto">気になるサークルに参加しよう</p>
            <div class="btn btn-primary mx-auto" style="width: 15rem;"><%=link_to "作ろう", new_circle_path, class:"text-white" %></div>
        </div>
    </div>
</div>
<% else %>
<div class="container">
    <div class="text-center h1 mt-100px">ようこそ！　サークルに！</div>
    <div class="row w-800px mt-100px">
        <div class="card mt-2 mr-2 col-sm m" style="height:10rem;">
            <div class="h4 mx-auto mt-3">イベントに参加</div>
            <p class="card-text mx-auto">自分の興味あるイベントを探してみよう</p>
            <div class="btn btn-primary mx-auto " style="width: 15rem;"><%=link_to "探そう", login_path, class:"text-white"%></div>
        </div>
        <div class="card mt-2 col-sm m" style="height:10rem;">
            <div class="h4 mx-auto mt-3">サークルに参加</div>
            <p class="card-text mx-auto">気になるサークルに参加しよう</p>
            <div class="btn btn-primary mx-auto " style="width: 15rem;"><%=link_to "探そう", login_path, class:"text-white" %></div>
        </div>
    </div>
    <div class="row w-800px">
        <div class="card mt-2 mr-2 col-sm m" style="height:10rem;">
            <div class="h4 mx-auto mmt-3">イベントを企画</div>
            <p class="card-text mx-auto">自分の興味あるイベントを探してみよう</p>
            <div class="btn btn-primary mx-auto " style="width: 15rem;"><%=link_to "企画してみよう", login_path, class:"text-white" %></div>
        </div>
        <div class="card mt-2 col-sm m " style="height:10rem;">
            <div class="h4 mx-auto mt-3">サークル作り</div>
            <p class="card-text mx-auto">気になるサークルに参加しよう</p>
            <div class="btn btn-primary mx-auto " style="width: 15rem;"><%=link_to "作ろう", login_path, class:"text-white" %></div>
        </div>
    </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="card mx-auto mt-2" style="width: 25rem;">
  <div class="h2 text-center mt-4">新規登録</div>
  <div class="text-center m" style="width: 20rem;">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class:"form-control" %>

      <%= f.label :email, "E-mail" %>
      <%= f.email_field :email, class:"form-control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class:"form-control" %>

      <%= f.label :password_confirmation, "確認パスワード" %>
      <%= f.password_field :password_confirmation, class:"form-control" %>

      <div class="mx-auto m-4" style="width: 10rem;">
        <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
<div class="mx-auto my-4" style="width: 50rem;">
    <div>
        <% if @user.id == current_user.id %>
        <div class="text-center h1"><%= @user.name%></div>
        <div class="mt-2 h2">自己紹介</div>
        <div class="mt-2 card mx-auto" style= "width: 35rem; height: 20rem;">
            <%=form_with model: @profile, url: user_profile_path(@user, @profile), local:true do |f|%>
                <%= f.text_area :content, class: 'form-control', style:"width: 35rem; height: 18rem;"%>
                <%= f.submit "編集"%>
            <% end %>
        </div>
        <% else %>
        <div class="text-center h1"><%= @user.name%></div>
        <div class="mt-2 h2">自己紹介</div>
        <div class="mt-2 card mx-auto" style= "width: 35rem; height: 20rem;">
            <%= @profile.content%>
        </div>
        <% end %>
        <% if @user.id == current_user.id %>
        <div class="mt-4">
            <div class="h2">企画したイベント</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.events.count > 0%>
                    <% @user.events.each do |event|%>
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to event.title, event_path(event.id), class:"pl-4" %></div>
                        <div class="pc h3"><%= link_to "編集", edit_event_path(event.id),  class:"pl-4" %></div>
                        <div class="pc h3"><%= link_to "削除", event_path(event.id), method: :delete,  class:"pl-4" %></div>
                    </div>    
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>現在企画したイベントはありません</div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="mt-4">
            <div class="h2">参加予定のイベント</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.jevents.count > 0%>
                    <% @user.events.each do |event|%>
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div class="pc h3"><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to event.title, event_path(event.id), class:"pl-4" %></div>
                    </div>
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>参加予定のイベントはありません</div>
                    </div>
                <% end %>    
            </div>    
        </div>
        <div class="mt-4">
            <div class="h2">参加サークル</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.jcircles.count > 0%>
                    <% @user.jcircle_circles.each do |circle| %>
                        <div class="pc h3"><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to circle.name, circle_path(circle.id), class:"pl-4"%></div>
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>現在所属サークルはありません</div>
                    </div>
                <% end %>       
            </div>    
        </div>
        <% else %>
        <div class="mt-4">
            <div class="h2">企画したイベント</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.events.count > 0%>
                    <% @user.events.each do |event|%>
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to event.title, event_path(event.id), class:"pl-4" %></div>
                    </div>    
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>現在企画したイベントはありません</div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="mt-4">
            <div class="h2">参加予定のイベント</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.jevents.count > 0%>
                    <% @user.events.each do |event|%>
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div class="pc h3"><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to event.title, event_path(event.id), class:"pl-4" %></div>
                    </div>
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>参加予定のイベントはありません</div>
                    </div>
                <% end %>    
            </div>    
        </div>
        <div class="mt-4">
            <div class="h2">参加サークル</div>
            <div class="mx-auto" style="width: 50rem;">
                <%if @user.jcircles.count > 0%>
                    <% @user.jcircle_circles.each do |circle| %>
                        <div class="pc h3"><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
                        <div class="pc h3"><%=link_to circle.name, circle_path(circle.id), class:"pl-4"%></div>
                    <% end %>
                <% else %>    
                    <div class="d-flex mt-3 pb-4 border-bottom">
                        <div>現在所属サークルはありません</div>
                    </div>
                <% end %>       
            </div>    
        </div>
        <%end%>
    </div>
</div>
<% end %>