config/routes.rb
Rails.application.routes.draw do

  root  'users#home'
  get    '/signup',  to: 'users#new'
  resources :users do
    resources :profiles
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :events do
    resources :comments, only: [:create, :destroy, :show] do
      post 'reply', to: 'comments#reply'
    end
    resources :jevents, only: [:create, :destroy]
  end
  resources :circles do 
    resources :jcircles, only: [:create, :destroy]
    
  end
   get 'genre', to: 'events#genre'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  geocoded_by :address
  after_validation :geocode
  has_many :jevents, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :jevent_users, through: :jevents, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 500 }
  validates :address, presence: true
  validates :hold, presence: true
  validates :genre_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :destroy]
  
  def index
    @events = Event.all();
    @genres = Genre.all();
  end
  
  def genre
    p "======"
    p params
    p "======"
    
    @genre_id = params[:genre_id]
    
    @genre = Genre.find(params[:genre_id]);
    @genres = Genre.all();
    @events = Event.where(genre_id: params[:genre_id])
    
    # redirect_to genre_path(@events)
  end
  
  def show
    @user = User.find(session[:user_id])
    @event = Event.find(params[:id])
    @comments = Comment.where(event_id: params[:id])
  end
  
  def new
    # @event = Event.new
    @event = current_user.events.build if logged_in?
    @genres = Genre.all();
  end

  def create
    p "======"
    p params
    p "======"
    
    @genres = Genre.all();
    @event = current_user.events.new(event_params)
    @event.genre_id = params[:genre_id]
    if @event.save
      @jevent = current_user.jevents.create(event_id: @event.id)
      flash[:success] = "Event created!"
      redirect_to events_path
      
    else
      
      render 'new'
    end
  end
  
  def edit
    @event = Event.find(params[:id])
    @genres = Genre.all()
  end
  
  def update
     @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:success] = "更新しました!"
        redirect_to event_path(@event)
      else
         @genres = Genre.all()
         render 'new'
      end
  end

  def destroy
    @user = current_user
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path(@user)
  end

  private

    def event_params
      params.require(:event).permit(:title, :body, :address, :hold)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  
end

app/views/events/_form.html.erb
<div class="h1 text-center">イベント企画</div>
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="mt-2">
    <label class="form-label">イベント名</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <label class="form-label">イベント詳細</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="field">
    <label class="form-label">場所</label>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="field">
    <label class="form-label">開催日時</label>
    <%= f.datetime_field :hold, class: 'form-control', min: Date.current %>
  </div>
  <div class="field">
    <label class="form-label">ジャンルの種類</label>
    <select name="genre_id">
      <% @genres.each do |genre| %>
        <option value="<%= genre.id %>"><%= genre.name %></option>
      <% end %>
    </select>
  </div>
  <div class="mx-auto" style="width: 10rem;">
    <%= f.submit "作成", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="card mx-auto mt-2" style="width: 25rem;">
  <%= render 'events/form' %>
</div>

app/views/events/genre.html.erb
<div class="d-flex">
    <div class="h1">
        イベント
    </div>
    <div class="ml-2 mt-2">
        <%= form_with url: genre_path, method: :get, class:"d-flex", local: true do |f| %>
            <select name="genre_id" class="form-control me-2">
              <% @genres.each do |genre| %>
                  <% if genre.id == @genre_id %>
                  <option value="<%= genre.id %>" selected><%= genre.name %></option>
                  <% else %>
                  <option value="<%= genre.id %>"><%= genre.name %></option>
                  <% end %>
              <% end %>
            </select>
            <%= f.submit "検索", class:"btn btn-outline-success" %>
        <% end %>
    </div>
    <div class="ml-2 h1">
        <%= @genre.name%>
    </div>
</div>
<div class="mx-auto" style="width: 50rem;">
    <div class="h2"> 
    <% @events.each do |event|%>
        <div class="d-flex mt-3 pb-4 border-bottom">
            <div><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
            <div>
                <%= link_to event.title, event_path(event) %>
            </div>
          
        </div>
    <% end %>    
    </div>
</div>

app/views/events/index.html.erb
<div class="d-flex s">
    <div class="h1">
        イベント
    </div>
    <div class="ml-2">
        <%= form_with url: genre_path, method: :get, class:"d-flex", local: true do |f| %>
            <select name="genre_id" class="form-control me-2">
              <% @genres.each do |genre| %>
              <option value="<%= genre.id %>"><%= genre.name %></option>
              <% end %>
            </select>
            <%= f.submit "検索", class:"btn btn-outline-success" %>
        <% end %>
    </div>
</div>
<div class="mx-auto" style="width: 50rem;">
    <div class="h2"> 
    <% @events.each do |event|%>
        <div class="d-flex mt-3 pb-4 border-bottom">
            <div><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
            <div class="pc">
                <%= link_to event.title, event_path(event), class:"pl-4"%>
            </div>
        </div>
    <% end %>    
    </div>
</div>

app/views/events/new.html.erb
<div class="card mx-auto mt-2" style="width: 25rem;">
  
  <%= render 'events/form' %>
</div>

app/views/events/show.html.erb
<div class="mx-auto my-4" style="width: 40rem;">
  <div class="d-flex">
    <div class="h1 mr-auto"><%= @event.title%></div>
    <div class="h4">製作者<%= @event.user.name %></div>
  </div>
  <% if already_ejained?(@event)%>
    <div class="ml-auto"><%= button_to '参加をやめる',  event_jevent_path(@event), method: :delete%></div>
  <% else %>
    <div class="mr-auto"><%= button_to '参加する',  event_jevents_path(@event) %></div>
  <% end %>
  
  <div class="d-flex">
    <div><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 15rem;" %></div>
    <div>
      <ul>
        <li>参加人数</li>
        <li>時間: <%= l @event.hold %></li>
        <li>
          場所: <%= @event.address %>
          <div id='map'>
          </div>
        </li>
        
      </ul>
    </div>
  </div>
  <div class="mt-2 h2">イベント詳細</div>
  <div class="mt-2 card mx-auto" style= "width: 35rem; height: 20rem;">
    <div><%= @event.body%></div>
  </div>
  <div class="mt-2 h2">コメント一覧</div>
  <div>
    <%= form_with model: @comment, url: event_comments_path(@event) do |f| %>
      <div>
        <%= f.text_field :text, class: 'form-control' %>
      </div>
      <div class="text-right">
        <%= f.submit "作成", class: "btn btn-primary" %>
      </div>
    <% end %>
    <div>
        <%if @event.comments.count > 0 %>
          <% @event.comments.each do |c| %>
           <div class="mt-2 pl-2  mx-auto border-bottom" style= "width: 40rem; height: 4rem;">
             <div><%= c.user.name %></div>
             <div class="h5"><%= link_to c.text, event_comment_path(@event, c) %></div>
            </div>
          <% end %>
        <% else %>    
            <div class="d-flex mt-3 pb-4 border-bottom">
                <div>コメントはありません</div>
            </div>  
        <% end %>    
    </div>
    <div class="mt-2 h2">イベント参加者</div>
    <div>
        <%if @event.jevents.count > 0 %>
          <% @event.jevents.each do |jevent| %>
           <div class="mt-2 pl-2  mx-auto border-bottom" style= "width: 40rem; height: 4rem;">
             <div><%= link_to jevent.user.name, user_path(jevent.user) %></div>
            </div>
          <% end %>
        <% else %>    
            <div class="d-flex mt-3 pb-4 border-bottom">
                <div>コメントはありません</div>
            </div>  
        <% end %>    
    </div>
  </div>
</div>
<style>
#map{
  width: 200px;
  height: 200px;
}
</style>

<script>
  let map

  function initMap(){
    geocoder = new google.maps.Geocoder()
    var test ={lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};

    map = new google.maps.Map(document.getElementById('map'), {
      center: test,
      zoom: 15,
    });

    var contentString = '住所：<%= @event.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    marker = new google.maps.Marker({
      position:  test,
      map: map,
      title: contentString
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnl3r_XitGNoWCaZvTVKaQh0fclJMJXmQ&callback=initMap" async defer></script>