config/routes.rb
Rails.application.routes.draw do

  root  'users#home'
  get    '/signup',  to: 'users#new'
  resources :users do
    resources :profiles
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :events do
    resources :comments, only: [:create, :destroy, :show] do
      post 'reply', to: 'comments#reply'
    end
    resources :jevents, only: [:create, :destroy]
  end
  resources :circles do 
    resources :jcircles, only: [:create, :destroy]
    
  end
   get 'genre', to: 'events#genre'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/circle.rb
class Circle < ApplicationRecord
  belongs_to :user
  has_many :jcircles, dependent: :destroy
  has_many :jcircle_users, through: :jcircles, source: :users
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 300 }
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :destroy]
  
  def index
    @circles = Circle.all();
  end
  
  def show
    @circle = Circle.find(params[:id])
  end
  
  def new
    # @event = Event.new
    @circle = current_user.circles.build if logged_in?
  end

  def create
    @circle = current_user.circles.new(circle_params)
    if @circle.save
      flash[:success] = "Micropost created!"
      redirect_to circles_path
      
    else
      render 'new'
    end
  end
  
  def edit
    @circle = Circle.find(params[:id])
  end
  
  def update
    @circle = Circle.find(params[:id])
      if @circle.update(circle_params)
        flash[:success] = "更新しました!"
        redirect_to circle_path(@circle)
      else
         render 'new'
      end
  end

  def destroy
  end

  private

    def circle_params
      params.require(:circle).permit(:name, :body)
    end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<div class="h1 text-center">サークル制作</div>
  <%= form_for(@circle) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="mt-2">
      <label class="form-label">サークル名</label>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="field">
      <label class="form-label">サークル内容</label>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <div class="mx-auto" style="width: 10rem;">
    <%= f.submit "作成", class: "btn btn-primary btn-block" %>
  </div>
  <% end %>
</div>

app/views/circles/edit.html.erb
<div class="card mx-auto mt-2" style="width: 25rem;">
  <%= render 'circles/form' %>
</div>

app/views/circles/index.html.erb
<div class="h1">サークル</div>
<div class="mx-auto" style="width: 50rem;">
  <div class="h2"> 
    <% @circles.each do |circle|%>
      <div class="d-flex mt-3 pb-4 border-bottom">
        <div ><%= image_tag 'no_mage.jpeg' , class: "image", style: "width: 10rem;" %></div>
        <div class="pc">
            <%= link_to circle.name, circle_path(circle), class:"pl-4" %>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/circles/new.html.erb
<%= form_for(@circle) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, class: 'field' %>
  </div>
  <div class="field">
    <%= f.text_area :body, class: 'field field-t' %>
  </div>
  <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/circles/show.html.erb
<div class="mx-auto my-4" style="width: 40rem;">
  <div class="d-flex">
    <div class="h1"><%= @circle.name%></div>
    <div class="h1">製作者<%= @circle.user.name%></div>
    <% if current_user.id == @circle.user.id%>
      <ul>
        <li><%= link_to '編集', edit_circle_path(@circle) %></li>
        <li><%= link_to '削除', circle_path(@circle), method: :delete %></li>
      </ul>
    <% end %>
  </div>  
  <% if already_cjained?(@circle)%>
    <div class="ml-auto"><%= button_to '参加をやめる', circle_jcircle_path(@circle), method: :delete%></div>
  <% else %>
    <div class="ml-auto"><%= button_to '参加する', circle_jcircles_path(@circle) %></div>
  <% end %>
  <div class="mt-2 h2">サークル活動</div>
  <div class="mt-2 card mx-auto" style= "width: 35rem; height: 20rem;">
      <div><%= @circle.body%></div>
  </div>
  <div class="mt-2 h2">所属メンバー</div>
  <% @circle.jcircles.each do |jcircle| %>
    <div class="d-flex">
      <div><%= jcircle.user.name %></div>
    </div>
  <% end %>
</div>