config/routes.rb
Rails.application.routes.draw do

  root  'users#home'
  get    '/signup',  to: 'users#new'
  resources :users do
    resources :profiles
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :events do
    resources :comments, only: [:create, :destroy, :show] do
      post 'reply', to: 'comments#reply'
    end
    resources :jevents, only: [:create, :destroy]
  end
  resources :circles do 
    resources :jcircles, only: [:create, :destroy]
    
  end
   get 'genre', to: 'events#genre'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circle.rb
class Circle < ApplicationRecord
  belongs_to :user
  has_many :jcircles, dependent: :destroy
  has_many :jcircle_users, through: :jcircles, source: :users
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 300 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :replies, dependent: :destroy
  validates :text, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  geocoded_by :address
  after_validation :geocode
  has_many :jevents, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :jevent_users, through: :jevents, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 500 }
  validates :address, presence: true
  validates :hold, presence: true
  validates :genre_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :events
  validates :name, presence: true, length: { maximum: 500 }
end

app/models/jcircle.rb
class Jcircle < ApplicationRecord
  belongs_to :circle
  belongs_to :user
  validates_uniqueness_of :circle_id, scope: :user_id
end

app/models/jevent.rb
class Jevent < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :comment
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :jevents, dependent: :destroy
  has_many :circles, dependent: :destroy
  has_many :jcircles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :profiles, dependent: :destroy
  has_many :jcircle_circles, through: :jcircles, source: :circle
  has_many :jevent_events, through: :jevents, source: :event
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    if logged_in?
      @user = User.find(session[:user_id])
    end
  end
  def show
    puts "======"
    puts params[:id]
    puts "======"
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: params[:id])
    puts "======"
    puts @profile
    puts "======"
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)# 実装は終わっていないことに注意!
    if @user.save
      @user.profiles.create(content: 'よろしくお願いします')
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
   @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        flash[:success] = "更新しました!"
        redirect_to user_path(@user)
    else
         
        render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
end

app/helpers/jcircles_helper.rb
module JcirclesHelper
  def already_cjained?(circle)
    current_user.jcircles.exists?(circle_id: circle.id)
  end
end

app/helpers/jevents_helper.rb
module JeventsHelper
  def already_ejained?(event)
    current_user.jevents.exists?(event_id: event.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def e_d_user(event)
    current_user == event.user_id
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="container">
    <nav>
      <ul>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Contact", '#' %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="mb-4">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div><%= link_to "Event_app", root_path, class:"nav-link" %></div>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to current_user.name, '#', class:"nav-link" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings" %></li>
              <li class="divider"></li>
              <li>
                <%= button_to 'Log out', logout_path, :method => :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class:"nav-link" %></li>
        <% end %>
      </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EVENT_APP</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
    <!--<%= debug(params) if Rails.env.development? %>-->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>